// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaFCvmltlW8pwp5er_P7xv2yZqv2FJM8',
    appId: '1:579805485866:android:7e008d6efcf22c0fa71c53',
    messagingSenderId: '579805485866',
    projectId: 'eve-lam',
    storageBucket: 'eve-lam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48IX4YMZN6Do1cwR77q581OIOgtM4yHI',
    appId: '1:579805485866:ios:64f21ff400f23b9ca71c53',
    messagingSenderId: '579805485866',
    projectId: 'eve-lam',
    storageBucket: 'eve-lam.appspot.com',
    androidClientId: '579805485866-3tpok6cf0bo8m3t9rnnr1m003nanjrg0.apps.googleusercontent.com',
    iosClientId: '579805485866-lb41b0sv3b8o84l11vg96f4toodqg99d.apps.googleusercontent.com',
    iosBundleId: 'com.lamkhil.eveTest',
  );
}
